import flet as ft
import unicodedata
import os
import re

try:
    from pypdf import PdfReader
    from reportlab.pdfgen import canvas
    from reportlab.lib.pagesizes import A4
except ImportError:
    import subprocess
    subprocess.check_call(["pip", "install", "pypdf", "reportlab"])
    from pypdf import PdfReader
    from reportlab.pdfgen import canvas
    from reportlab.lib.pagesizes import A4


def filter_amharic_punctuation(text: str) -> str:
    """
    Remove Amharic punctuation marks from text.
    Removes: ፡ (word separator), ። (period), ፣ (comma), ፥ (colon), 
             ፦ (semicolon), ፧ (question mark), ፨ (exclamation)
    """
    # Amharic punctuation Unicode ranges
    # ፡ U+1361, ። U+1362, ፣ U+1363, ፤ U+1364, ፥ U+1365, ፦ U+1366, ፧ U+1367, ፨ U+1368
    amharic_punctuation = re.compile(r'[\u1361-\u1368]')
    return amharic_punctuation.sub('', text)


def convert_amharic_to_latin(text: str) -> str:
    """Convert Amharic text to Latin sound representation."""
    # First, filter out Amharic punctuation
    text = filter_amharic_punctuation(text)
    
    base_consonants = {
        'ሀ': 'h', 'ለ': 'l', 'ሐ': 'h', 'መ': 'm', 'ሠ': 's',
        'ረ': 'r', 'ሰ': 's', 'ሸ': 'sh', 'ቀ': 'q', 'በ': 'b',
        'ተ': 't', 'ቸ': 'ch', 'ኀ': 'h', 'ነ': 'n', 'ኘ': 'ny',
        'አ': 'a', 'ከ': 'k', 'ኸ': 'h', 'ወ': 'w', 'ዐ': 'a',
        'ዘ': 'z', 'ዠ': 'zh', 'የ': 'y', 'ደ': 'd',
        'ጀ': 'j', 'ገ': 'g', 'ጠ': 't', 'ጨ': 'ch',
        'ጰ': 'p', 'ጸ': 'ts', 'ፀ': 'ts', 'ፈ': 'f', 'ፐ': 'p',
    }
    vowel_suffixes = ['a', 'u', 'i', 'a', 'e', '', 'o']

    amharic_to_sound = {}
    for first_order_char, cons in base_consonants.items():
        base_code = ord(first_order_char)
        for order in range(7):
            char_code = base_code + order
            if 0x1200 <= char_code <= 0x137F:
                syllable = chr(char_code)
                try:
                    name = unicodedata.name(syllable)
                    if 'ETHIOPIC' not in name:
                        continue
                except (ValueError, TypeError):
                    continue
                amharic_to_sound[syllable] = cons + vowel_suffixes[order]

    extra_mapping = {
        'ቈ': 'qwa', 'ቊ': 'qwi', 'ቋ': 'qwa', 'ቌ': 'qwe', 'ቍ': 'qw',
        'ኈ': 'hwa', 'ኊ': 'hwi', 'ኋ': 'hwa', 'ኌ': 'hwe', 'ኍ': 'hw',
        'ዀ': 'hwa', 'ዂ': 'hwi', 'ዃ': 'hwa', 'ዄ': 'hwe',
        'ጐ': 'gwa', 'ጒ': 'gwi', 'ጓ': 'gwa', 'ጔ': 'gwe', 'ጕ': 'gw',
    }
    amharic_to_sound.update(extra_mapping)
    
    result = []
    for ch in text:
        result.append(amharic_to_sound.get(ch, ch))
    return ''.join(result)


def extract_text_from_pdf(pdf_file_path: str) -> str:
    reader = PdfReader(pdf_file_path)
    return "".join(page.extract_text() or "" for page in reader.pages)


def create_pdf_from_text(text: str, output_path: str, title: str = "Translated Document"):
    """Create a PDF with the given text."""
    c = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 16)
    c.drawString(72, height - 72, title)
    c.setFont("Helvetica", 10)
    c.drawString(72, height - 92, "Generated by Amharic → Latin Converter")
    c.line(72, height - 100, width - 72, height - 100)

    c.setFont("Helvetica", 11)
    y_position = height - 130
    margin = 72
    line_height = 14
    max_width = width - 2 * margin
    line = ""

    for word in text.split():
        test_line = line + " " + word if line else word
        if len(test_line) * 6 > max_width:
            c.drawString(margin, y_position, line)
            y_position -= line_height
            line = word
            if y_position < margin:
                c.showPage()
                c.setFont("Helvetica", 11)
                y_position = height - margin
        else:
            line = test_line

    if line:
        c.drawString(margin, y_position, line)
    c.save()


async def main(page: ft.Page):
    page.title = "Amharic → Latin Converter"
    page.theme_mode = ft.ThemeMode.LIGHT
    page.padding = 20
    page.scroll = ft.ScrollMode.AUTO
    page.window.width = 900
    page.window.height = 800

    state = {"selected_pdf_name": None, "selected_pdf_path": None}

    # --- Widgets ---
    status_text = ft.Text("", italic=True, color=ft.Colors.GREY_600)
    pdf_status = ft.Text("No PDF selected", italic=True, color=ft.Colors.GREY_600)
    char_counter_input = ft.Text("0 characters", size=12, color=ft.Colors.GREY_600)
    char_counter_output = ft.Text("0 characters", size=12, color=ft.Colors.GREY_600)

    input_text = ft.TextField(
        label="Amharic Text",
        hint_text="Enter Amharic text here, or upload a PDF...",
        multiline=True,
        min_lines=4,
        max_lines=10,
        expand=True,
        border_radius=10,
    )

    output_text = ft.TextField(
        label="Latin Transliteration",
        hint_text="Transliterated text will appear here...",
        multiline=True,
        min_lines=4,
        max_lines=10,
        expand=True,
        read_only=True,
        border_radius=10,
        border_color=ft.Colors.GREEN_400,
    )

    # FilePicker
    file_picker = ft.FilePicker()
    save_picker = ft.FilePicker()
    page.services.append(file_picker)
    page.services.append(save_picker)

    def update_char_count(e):
        char_counter_input.value = f"{len(input_text.value or '')} characters"
        page.update()

    input_text.on_change = update_char_count

    def convert_text(e):
        text = input_text.value or ""
        if text.strip():
            try:
                result = convert_amharic_to_latin(text)
                output_text.value = result
                char_counter_output.value = f"{len(result)} characters"
                status_text.value = f"✓ Converted {len(text)} → {len(result)} characters"
                status_text.color = ft.Colors.GREEN_700
            except Exception as err:
                status_text.value = f"✗ Error: {err}"
                status_text.color = ft.Colors.RED_700
        else:
            output_text.value = ""
            char_counter_output.value = "0 characters"
            status_text.value = "Please enter some text to convert"
            status_text.color = ft.Colors.GREY_600
        page.update()

    def clear_text(e):
        input_text.value = ""
        output_text.value = ""
        char_counter_input.value = "0 characters"
        char_counter_output.value = "0 characters"
        status_text.value = ""
        pdf_status.value = "No PDF selected"
        pdf_status.color = ft.Colors.GREY_600
        state["selected_pdf_name"] = None
        state["selected_pdf_path"] = None
        page.update()

    def copy_output(e):
        if output_text.value:
            page.set_clipboard(output_text.value)
            status_text.value = "✓ Copied to clipboard!"
            status_text.color = ft.Colors.GREEN_700
            page.update()

    async def pick_file_click(e):
        files = await file_picker.pick_files(
            allow_multiple=False,
            file_type=ft.FilePickerFileType.CUSTOM,
            allowed_extensions=["pdf"],
        )
        if files:
            file = files[0]
            state["selected_pdf_name"] = file.name
            state["selected_pdf_path"] = file.path
            size_mb = file.size / (1024 * 1024)
            pdf_status.value = f"📄 {file.name} ({size_mb:.2f} MB)"
            pdf_status.color = ft.Colors.GREEN_700
            try:
                extracted = extract_text_from_pdf(file.path)
                input_text.value = extracted
                char_counter_input.value = f"{len(extracted)} characters"
                status_text.value = f"✓ Extracted {len(extracted)} characters. Click Convert."
                status_text.color = ft.Colors.GREEN_700
            except Exception as err:
                status_text.value = f"✗ PDF Extract Error: {err}"
                status_text.color = ft.Colors.RED_700
            page.update()

    async def save_file_click(e):
        if not output_text.value:
            status_text.value = "✗ Nothing to export. Convert text first."
            status_text.color = ft.Colors.RED_700
            page.update()
            return

        suggested = "translated_document.pdf"
        if state["selected_pdf_name"]:
            base = os.path.splitext(state["selected_pdf_name"])[0]
            suggested = f"{base}_latin.pdf"

        save_path = await save_picker.save_file(
            file_name=suggested,
            file_type=ft.FilePickerFileType.CUSTOM,
            allowed_extensions=["pdf"],
        )
        if save_path:
            try:
                title = os.path.basename(save_path).replace('.pdf', '')
                create_pdf_from_text(output_text.value, save_path, f"{title} (Latin)")
                status_text.value = f"✓ Saved to: {save_path}"
                status_text.color = ft.Colors.GREEN_700
            except Exception as err:
                status_text.value = f"✗ Save Error: {err}"
                status_text.color = ft.Colors.RED_700
            page.update()

    # --- Layout ---
    header = ft.Column([
        ft.Row([
            ft.Icon(ft.Icons.TRANSLATE, size=40, color=ft.Colors.BLUE_700),
            ft.Text("Amharic to Latin Converter",
                    style=ft.TextThemeStyle.HEADLINE_MEDIUM,
                    weight=ft.FontWeight.BOLD),
        ]),
        ft.Text("Convert Ethiopic Ge'ez script into readable Latin. Text or entire PDFs supported.",
                style=ft.TextThemeStyle.BODY_LARGE),
        ft.Divider(),
    ])

    file_section = ft.Container(
        content=ft.Row([
            ft.FilledButton(
                "📄 Select Amharic PDF",
                icon=ft.Icons.UPLOAD_FILE,
                on_click=pick_file_click,
                style=ft.ButtonStyle(bgcolor=ft.Colors.BLUE_700, color=ft.Colors.WHITE),
            ),
            pdf_status,
        ], alignment=ft.MainAxisAlignment.START),
        padding=10,
        bgcolor=ft.Colors.GREY_100,
        border_radius=8,
    )

    input_output_row = ft.Row([
        ft.Column([
            ft.Text("Input (Amharic)", weight=ft.FontWeight.BOLD),
            input_text,
            char_counter_input,
        ], expand=True),
        ft.Column([
            ft.Text("Output (Latin)", weight=ft.FontWeight.BOLD),
            output_text,
            char_counter_output,
        ], expand=True),
    ])

    action_buttons = ft.Row([
        ft.FilledButton(
            "🔄 Convert to Latin",
            icon=ft.Icons.TRANSLATE,
            on_click=convert_text,
            style=ft.ButtonStyle(bgcolor=ft.Colors.BLUE_500, color=ft.Colors.WHITE),
        ),
        ft.OutlinedButton("📋 Copy Output", icon=ft.Icons.COPY, on_click=copy_output),
        ft.FilledButton(
            "💾 Export to PDF",
            icon=ft.Icons.PICTURE_AS_PDF,
            on_click=save_file_click,
            style=ft.ButtonStyle(bgcolor=ft.Colors.GREEN_600, color=ft.Colors.WHITE),
        ),
        ft.TextButton("🗑️ Clear All", icon=ft.Icons.CLEAR, on_click=clear_text),
    ], alignment=ft.MainAxisAlignment.START, wrap=True)

    page.add(
        header,
        ft.Divider(height=10),
        file_section,
        ft.Divider(height=10),
        input_output_row,
        ft.Container(status_text, padding=5),
        action_buttons,
        ft.Container(
            content=ft.Text(
                "💡 Tip: Upload a PDF with Amharic text to automatically extract and convert it",
                size=11,
                color=ft.Colors.GREY_600,
                italic=True,
            ),
            padding=5,
        ),
    )


if __name__ == "__main__":
    ft.run(main)
