[project]
name = "self-controle"
version = "0.1.0"
description = "Daily blueprint + self-control tracker"
requires-python = ">=3.10"
dependencies = [
    "flet>=1.0.1",
    "flet-charts",
    "flet-android-notifications",
]

[tool.flet]
product = "Self Control"
org = "com.example"


[tool.flet.android.permission]
"android.permission.POST_NOTIFICATIONS" = true
"android.permission.SCHEDULE_EXACT_ALARM" = true
"android.permission.RECEIVE_BOOT_COMPLETED" = true

[tool.flet.app]
path = "src"